[features]
seeds = false
skip-lint = false
[programs.localnet]
ej1 = "GQ5Wi1iyf328x9fMyahYV8ErWkLfX2Hav3qKJ7e5w3Kz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/francisco/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
